#!/bin/csh

set CASEID = 0
set DIRECT = ""
set RANDOM = "-define RANDOM"
set GUIDEF = ""
set COVDEF = ""
set DEFINE = "-define DELAY_SRAM"
set SVSEED = "random"
set DUMPEN = ""
set ASSERT = ""

while ($#argv>0)
	if ( "$argv[1]" == "-case" ) then
		shift
		set CASEID = $argv[1]
	else if ( "$argv[1]" == "-direct" ) then
		set DIRECT = "-define DIRECT"
		set RANDOM = ""
	else if ( "$argv[1]" == "-random" ) then
		set RANDOM = "-define RANDOM"
	else if ( "$argv[1]" == "gui" ) then
		set GUIDEF = "-gui"
	else if ( "$argv[1]" == "cov" ) then
		set COVDEF = "-coverage a -covdut POOL_OUT_U -covfile exclude_signal.ccf"
	else if ( "$argv[1]" == "-seed" ) then
		shift
		set SVSEED = $argv[1]
	else if ( "$argv[1]" == "-dump" ) then
		set DUMPEN = "-define DUMP_EN"
	else if ( "$argv[1]" == "-assert" ) then
		set ASSERT = "-define ASSERT_ON"
	else if ( "$argv[1]" == "-define" ) then
		shift
		set DEFINE = "$DEFINE -define $argv[1]"
	endif
	shift
end

rm ./dump/*
irun -access +rwc -sv -64bit -f filelist.f -timescale 1ns/1ps +testcase=$CASEID $DIRECT $RANDOM $COVDEF $GUIDEF $DUMPEN $ASSERT -svseed $SVSEED $DEFINE -l ./log/irun.log

set c = (`grep "from command line:" ./log/irun.log`)
set seed = `echo $c | cut -d ":" -f2`

set i = 0
set diff_data = `diff PSUMGB_data0_py.txt ./dump/PSUMGB_data0_rtl.txt`

if( ( "$diff_data" == "" )&&( "$diff_data" == "" ) ) then
	echo "seed $seed    PASS" >> ./log/result.log
	echo "seed $seed    PASS"
else
	echo "seed $seed    FAIL" >> ./log/result.log
	echo "seed $seed    FAIL"
endif



